# SPDX-License-Identifier: MIT
# Copyright (c) 2025 René Lacher

repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.4
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
