# SPDX-License-Identifier: MIT
# Copyright (c) 2025 René Lacher
# Kafka broker setup for Fraud Guard MVP project

services:
  kafka:
    image: apache/kafka:3.9.1
    container_name: kafka-kraft
    ports:
    - "9092:9092"  # Kafka broker port
    - "9093:9093"  # KRaft controller communication port
    restart: unless-stopped
    environment:
    # Single-node KRaft mode
    - KAFKA_NODE_ID=1
    - KAFKA_PROCESS_ROLES=broker,controller
    - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-kraft:9093
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-kraft:9092
    - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
    # Log directory inside container mapped to named volume
    - KAFKA_LOG_DIRS=/var/lib/kafka/data
    # Enable auto topic creation for MVP-context
    - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    healthcheck:
      # Minimal check if broker port is listening
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
    - kafka-data:/var/lib/kafka/data
    networks:
    - kafka-net

  producer:
    build:
      context: ../data
      args:
      - DATA_FILENAME=card_transdata.csv
    container_name: kafka-producer
    command: python3 producer.py
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka-net
    restart: on-failure

volumes:
  kafka-data:

networks:
  kafka-net:
    driver: bridge
