# SPDX-License-Identifier: MIT
# Copyright (c) 2025 René Lacher

name: Docker Compose Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file for Docker Compose
        run: echo "DATA_FILENAME=card_transdata.csv" > kafka/.env

      - name: Build Docker Compose services without cache
        run: docker compose -f kafka/docker-compose.yaml build --no-cache
