# SPDX-License-Identifier: MIT
# Copyright (c) 2025 René Lacher

name: Run Pytest with Coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt -r data/requirements.txt

      - name: Run tests with coverage
        run: pytest --cov=app --cov=data --cov-branch app/tests data/tests
